apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: logging
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.enabled: false
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    filter {
      if !([kubernetes][namespace] in ["demo", "logging", "ingress-nginx"]) {
        drop { }
      }

      if "No space left on device" in [message] or "disk pressure" in [message] {
        mutate { add_tag => ["storage_full"] }
      }

      if [kubernetes][labels][app] == "nginx" {
        grok {
          match => {
            "message" => "%{IPORHOST:client_ip} - %{DATA:remote_user} \\[%{HTTPDATE:timestamp}\\] \"%{WORD:method} %{DATA:request} HTTP/%{NUMBER:http_version}\" %{NUMBER:status:int} %{NUMBER:bytes:int} \"%{DATA:referrer}\" \"%{DATA:user_agent}\""
          }
        }
        date {
          match => ["timestamp", "dd/MMM/YYYY:HH:mm:ss Z"]
        }
      }
    }

    output {
      if "storage_full" in [tags] {
        elasticsearch {
          hosts => ["http://elasticsearch:9200"]
          index => "alerts-storage-%{+YYYY.MM.dd}"
        }
      } else {
        elasticsearch {
          hosts => ["http://elasticsearch:9200"]
          index => "logs-%{+YYYY.MM.dd}"
        }
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: logging
spec:
  selector:
    app: logstash
  ports:
    - name: beats
      port: 5044
      targetPort: 5044
    - name: http
      port: 9600
      targetPort: 9600
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.11.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5044
              name: beats
            - containerPort: 9600
              name: http
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: logstash-config
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
            - name: logstash-config
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config
